<h1>Single Dimension numpy array</h1>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
n1 = np.array([10,20,30,40,50,60,70,80,90,100])
n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
type(n1)

numpy.ndarray

<h1>MultiDimensional numpy array</h1>

In [10]:
n2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(n2)
n2

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

<h3>array of matrix with full then</h3>

In [14]:
n4 = np.full((3,3),11)
n4

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

<h3>numpy arra within arange</h3>

In [17]:
n5 = np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
n6 = np.arange(1,10,2)
n6

array([1, 3, 5, 7, 9])

<h3>Initialization numpy array with random integers</h3>

In [21]:
n7=np.random.randint(100,1000,10)
n7

array([666, 615, 785, 471, 594, 902, 625, 821, 107, 749])

<h3>initialization the array shape changes in a fraction of shape</h3>

In [24]:
n8=np.array([[10,20,40,50],[50,605,40,50],[10,13,23,50]])
n8.shape

(3, 4)

In [25]:
n8.shape=(4,3)
n8

array([[ 10,  20,  40],
       [ 50,  50, 605],
       [ 40,  50,  10],
       [ 13,  23,  50]])

<h1>Joining numpy array</h1>

In [26]:
a=np.array([10,20,40])
b=np.array([50,40,60])

In [27]:
np.vstack((a,b)) #joining the numpy as vertical stacking

array([[10, 20, 40],
       [50, 40, 60]])

In [28]:
np.hstack((a,b)) #joining the numpy as horizonatl stacking

array([10, 20, 40, 50, 40, 60])

In [29]:
np.column_stack((a,b)) #joining numpy as column stack

array([[10, 50],
       [20, 40],
       [40, 60]])

<h1>Numpy intersection and differences</h1>

In [30]:
x=np.array([10,20,30,40,50,60])

In [31]:
y=np.array([30,50,90,100,120,150])

In [32]:
np.intersect1d(x,y)

array([30, 50])

In [33]:
np.union1d(x,y)

array([ 10,  20,  30,  40,  50,  60,  90, 100, 120, 150])

In [37]:
print(np.setdiff1d(y,x))
print(np.setdiff1d(x,y))

[ 90 100 120 150]
[10 20 40 60]


<h3>Addition of numpy arrays</h3>

In [41]:
t = np.array([50,20])
s = np.array([30,40])

In [42]:
np.sum([t,s])

140

In [43]:
np.sum([t,s],axis=0)

array([80, 60])

In [44]:
np.sum([t,s],axis=1)

array([70, 70])

<h3>Numpy array mathematics</h3>

In [45]:
p=np.array([10,20,30])

In [49]:
print(p+1)
print(p/2)
print(p**2)
print(p-2)

[11 21 31]
[ 5. 10. 15.]
[100 400 900]
[ 8 18 28]


<h3>numpy math functions</h3>

In [50]:
nn = np.array([10,20,30,60])
np.mean(nn)

30.0

In [51]:
np.std(nn)

18.708286933869708

In [52]:
np.median(nn)

25.0

<h1>Saving and loading numpy array</h1>

In [53]:
n11=np.array([10,20,30,40,60])

In [54]:
np.save('ml',n11)

In [55]:
np.load('ml.npy')

array([10, 20, 30, 40, 60])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.ones(2)

array([1., 1.])

In [60]:
a = np.array([1,2,3])
print(type(a), a.shape,a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [61]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [64]:
e = np.random.random((4,4))
e

array([[0.24818968, 0.4830199 , 0.50025919, 0.05797656],
       [0.70791542, 0.37188069, 0.50848348, 0.42632597],
       [0.11921107, 0.2909699 , 0.67338075, 0.78808025],
       [0.49052272, 0.36396669, 0.55819249, 0.89112185]])

### boolean array indexing

In [65]:
a = np.array([[2,3],[4,5],[5,6]])
bool_idx=(a>3)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [66]:
print(a[bool_idx])
print(a[a>2])

[4 5 5 6]
[3 4 5 5 6]


In [67]:
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2],dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


### Array math

In [69]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
x = np.array([[1,5],[3,7]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[2. 7.]
 [4. 9.]]
[[2. 7.]
 [4. 9.]]


In [71]:
print(x-y)

[[0. 3.]
 [2. 5.]]


In [76]:
print(x*y)
print("mul = ",np.multiply(x,y))
print(np.subtract(x,y))

[[ 1. 10.]
 [ 3. 14.]]
mul [[ 1. 10.]
 [ 3. 14.]]
[[0. 3.]
 [2. 5.]]


In [75]:
print(x/y)
print(np.divide(x,y))

[[1.  2.5]
 [3.  3.5]]
[[1.  2.5]
 [3.  3.5]]


In [77]:
print(np.sqrt(x))

[[1.         2.23606798]
 [1.73205081 2.64575131]]


### dot product

In [80]:
v = np.array([[1,2],[4,5]])
w = np.array([[4,5],[7,8]])
print(v.dot(w))
print(np.dot(v,w))# I prefer this one

[[18 21]
 [51 60]]
[[18 21]
 [51 60]]


In [81]:
print(v @ w)

[[18 21]
 [51 60]]


# Performance computing on arrays

In [83]:
import numpy as np

x = np.array([[1, 2], [3, 4]])  # Properly define the array
print(np.sum(x))               # Sum of all elements
print(np.sum(x, axis=0))       # Sum of each column
print(np.sum(x, axis=1))       # Sum of each row


10
[4 6]
[3 7]


In [90]:
np.transpose(x)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Broadcasting in numpy

In [85]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([1,2,1])
y = np.empty_like(x)

for i in range(3):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  4  4]
 [ 5  7  7]
 [ 8 10 10]]


In [88]:
vv = np.tile(v, (3,1))
print(vv)

[[1 2 1]
 [1 2 1]
 [1 2 1]]


In [89]:
y = x + vv
print(y)

[[ 2  4  4]
 [ 5  7  7]
 [ 8 10 10]]


### uniform samples

In [95]:
np.random.uniform(low=0.0, high=1.0, size=None)

0.7889404808746113

In [96]:
np.random.uniform(5,10, size=5)

array([6.336156  , 7.82359248, 9.03199671, 7.80070158, 5.1736154 ])

In [97]:
np.random.uniform(size=5)

array([0.46628527, 0.76205782, 0.02301189, 0.50088385, 0.88310389])

### logspace

In [98]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

In [99]:
a = np.array([0.9,0.5,1,1.2,1.4,3.6])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([1, 1, 2, 2, 2, 4], dtype=int64)

### Expand dimensions

In [100]:
arr = np.array([8,14,1,8,11,4,9,4,4,1,13,13,11])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  1,  8, 11,  4,  9,  4,  4,  1, 13, 13, 11]])

In [101]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

In [102]:
arr = np.array([[8],[14],[1],[8],[11],[2]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  2])

In [103]:
a = np.array([0,0,1,1,1,0]) 
np.count_nonzero(a) # count the number of zero elements

3

In [104]:
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

In [105]:
#np.argmax(a, axis=None, out=None)
arr = np.array([[6.23,0.64,1.23,1.35]])
np.argmax(arr)

0

In [106]:
np.argmin(arr)

1

In [107]:
#np.sort(a, axis=-1, kind=None, order=None)
np.sort(arr)

array([[0.64, 1.23, 1.35, 6.23]])

In [109]:
np.abs(arr) # it returns the absolute value

array([[6.23, 0.64, 1.23, 1.35]])

In [113]:
print(np.round(arr, decimals=0))
print(np.round(arr, decimals=1))

[[6. 1. 1. 1.]]
[[6.2 0.6 1.2 1.4]]


In [112]:
a = np.random.random(size=(3,4))
a

array([[0.02555277, 0.25827765, 0.15004684, 0.86413465],
       [0.94365389, 0.59004162, 0.49543295, 0.61681253],
       [0.08445259, 0.35787026, 0.29739249, 0.13839665]])

In [114]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [115]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [116]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [117]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [118]:
a[np.where(a<5)]

array([0, 1, 2, 3, 4])

In [119]:
np.put(arr,[1,2],[6,7]) # replaces specified elements of an array with give values
arr

array([ 0,  6,  7, -4,  5,  6,  7,  2,  3])

In [123]:
#copyto(dst, src, casting='same_kind', where=True)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Before arr1", arr1)
print("Before  arr2", arr2)
np.copyto(arr1,arr2)
print("After arr1", arr1)
print("After arr2", arr2)

Before arr1 [1 2 3]
Before  arr2 [4 5 6]
After arr1 [4 5 6]
After arr2 [4 5 6]


### extract unique elements from both Arrays

In [124]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,4,9,4,36])
np.setxor1d(a,b)

array([ 2,  3,  5,  6,  9, 36])

In [125]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A, 2) ## splits the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [126]:
np.hsplit(A,4)

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

In [135]:
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

### comparing two arrays

In [136]:
a = np.array([0.25,0.4,0.6,0.32])
b = np.array([0.26,0.3,2.7,0.32])
tolerance = 0.1 # total difference
np.allclose(a,b,tolerance)

False

In [142]:
tolerance = 0.1
np.allclose(a,b,tolerance)
print(np.abs(a - b) > tolerance)

[False  True  True False]


In [140]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

In [146]:
import pandas as pd
df = pd.DataFrame([['Mango',40],['Banana',140],['apple',240]], columns=['fruits','price'])

In [148]:
df['year'] = np.repeat(2020, df.shape[0])
df

fruits  price  year
0   Mango     40  2020
1  Banana    140  2020
2   apple    240  2020

### array printing options

In [149]:
np.set_printoptions(precision=2)
a = np.array([12.23456, 32.34535])
print(a)

[12.23 32.35]


In [150]:
np.set_printoptions(threshold=np.inf)

In [151]:
np.set_printoptions(linewidth=100) #default 75