In [2]:
import numpy as np

# 1. Creating arrays

In [45]:
arr = np.array([1, 2, 3]) # from list
arr1 = np.array([[1, 2], [3, 4]]) # multi dimensional array
zeros = np.zeros((2, 3))  # 2 rows, 3 columns 0's
ones = np.ones((3, 2))  # 3 rows, 2 columns of 1's
identity = np.eye(3)  # 3x3 identity matrix
arr_range = np.arange(0, 10, 2)  # from 0 to 10 escaping 2 elements
linspace = np.linspace(0, 1, 5)  # create 5 parts from 0 to 1
logspace = np.logspace(1, 3, num=5) # Generate 5 numbers spaced evenly on a logarithmic scale from 10^1 to 10^3
print(arr,arr1,zeros,ones,identity,arr_range,linspace,logspace, sep='\n')

[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  10.           31.6227766   100.          316.22776602 1000.        ]


# 2. Array properties

In [37]:
print('shape: ', arr1.shape) # shape of array row by columns
print('dimensions: ', arr1.ndim) # number of dimensions
print('data type: ', arr1.dtype) # data type
print('size: ', arr1.size) # number of elements
print('transpose of matrix: ', arr1.T)
print('itemsize: ', arr1.itemsize)

shape:  (2, 2)
dimensions:  2
data type:  int32
size:  4
transpose of matrix:  [[1 3]
 [2 4]]
itemsize:  4


# 3.Indexing and Slicing

In [17]:
print(arr1[1]) # single element
print(arr1[1:5]) # from 1 to 4
print(arr1[0,1]) # multi-dimensional indexing
print(arr1[arr1 > 1]) # boolean indexing

[3 4]
[[3 4]]
2
[2 3 4]


# 4. Mathematical operations

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # adding
result

array([5, 7, 9])

In [22]:
result = arr1 * 2
result

array([2, 4, 6])

In [25]:
print(arr1.sum())        # Sum of all elements
print(arr1.mean())       # Mean of elements
print(arr1.max())        # Maximum value
print(arr1.min())        # Minimum value

6
2.0
3
1


# 5. Datatype conversions

In [26]:
arr_float = np.array([1.1, 2.2, 3.3])
arr_int = arr_float.astype(int) # convert to int from float
print(arr_int)

[1 2 3]


In [27]:
arr_str = np.array(["10", "20", "30"])
arr_int = arr_str.astype(int) # convert to int from str
print(arr_int)

[10 20 30]


In [28]:
arr_int = np.array([1, 2, 3])
arr_float = arr_int.astype(float) # convert to float from int
print(arr_float)

[1. 2. 3.]


In [29]:
arr_int = np.array([1, 2, 3])
arr_str = arr_int.astype(str) # convert to str from int
print(arr_str)

['1' '2' '3']


In [30]:
arr_float = np.array([3.14, 2.71])
arr_str = arr_float.astype(str) # convert to str from float
print(arr_str)

['3.14' '2.71']


In [31]:
arr = np.array([1.5, 2.8, 3.9], dtype=float)
arr_new = arr.astype(int)  # Convert to integer
print(arr_new)

[1 2 3]


In [32]:
arr = np.array([1.1, 2.2, 3.3])
print(arr.dtype) # printing datatype

float64


In [33]:
arr = np.array([1.1, 2.2, 3.3], dtype=int) # changing datatype when creating an array
print(arr)

[1 2 3]


# 6.Broadcasting

In [38]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr + 5 #  scalar is broadcasted to match the shape of the array.
print(result) 


[6 7 8]


In [39]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])  # Shape (3,)
result = arr1 + arr2 # adding array with different shape
print(result)

[[11 22 33]
 [14 25 36]]


In [40]:
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([10, 20, 30])    # Shape (3,)
result = arr1 + arr2 # broadcasting with 1d and 2d array
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [41]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[10], [20]])           # Shape (2, 1)
result = arr1 * arr2 # multiplying arrays with incompatible shapes
print(result)

[[ 10  20  30]
 [ 80 100 120]]


# 7.Array From Existing Data

In [42]:
buffer = b'\x01\x02\x03\x04\x05\x06'

# Create an array from the buffer
arr = np.frombuffer(buffer, dtype=np.uint8)
print(arr)

[1 2 3 4 5 6]


In [43]:
# numpy.fromiter(iterable, dtype=float, count=-1)
# A list of numbers
iterable = [1, 2, 3, 4, 5]

# Convert the list into a NumPy array
arr = np.fromiter(iterable, dtype=int)

print(arr)

[1 2 3 4 5]


# 8. Numpy Array Iteration

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Iterate over rows using for loop
for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Iterate 2d array using nditer
for element in np.nditer(arr):
    print(element)

1
2
3
4
5
6


In [48]:
# Iterate with indices using ndenumerate
for idx, element in np.ndenumerate(arr):
    print(f"Index: {idx}, Value: {element}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6


# 9. Updating numpy array

In [49]:
arr = np.array([1, 2, 3, 4, 5])
arr.fill(9)  # Fill the array with 9
print(arr)

[9 9 9 9 9]


In [50]:
arr = np.array([0, 1, 2, 3, 4])
arr.put([0, 2, 4], [10, 20, 30])  # Replace elements at indices 0, 2, 4 with 10, 20, 30
print(arr)

[10  1 20  3 30]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])

#boolean indexing
arr[arr % 2 == 0] = 0  # Set all even numbers to 0
print(arr)

[1 0 3 0 5 0]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 99  # Assign 99 to the element at index 2
print(arr)

[ 1  2 99  4  5]


In [53]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = [10, 20, 30]  # Replace elements from index 1 to 3 with new values
print(arr)

[ 1 10 20 30  5]


# 10.Array Manipulation

In [56]:
arr = np.array([1, 5, 10, 15, 20])
clipped_arr = arr.clip(10, 20) # clip(min,max)
print(clipped_arr)

[10 10 10 15 20]


In [57]:
arr = np.array([1, 2, 3, 4])
flipped_arr = np.flip(arr) # flip method reverse an array along a specified axis flip(arr,axis=None)
print(flipped_arr)

[4 3 2 1]


In [58]:
arr = np.array([3, 1, 4, 1, 5, 9])
arr.sort() # sort an array
print(arr)

[1 1 3 4 5 9]


In [59]:
arr = np.array([1, 2, 2, 3, 3, 3])
unique_arr = np.unique(arr) # pring unique elements
print(unique_arr)

[1 2 3]


In [60]:
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5]) # append elements at last
print(new_arr)

[1 2 3 4 5]


In [61]:
arr = np.array([1, 2, 4, 5])
new_arr = np.insert(arr, 2, 3)  # Insert 3 at index 2
print(new_arr)

[1 2 3 4 5]


In [64]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [1, 3]) # delete the elements on specified index
print(new_arr)

[1 3 5]


In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.transpose()
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [66]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
raveled_arr = arr.ravel() # make flattened 1d array
print(raveled_arr)

[1 2 3 4 5 6]


In [67]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
flattened_arr = arr.flatten() # copy of array into 1d array
print(flattened_arr)

[1 2 3 4 5 6]


In [68]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [69]:
arr = np.array([1, 2, 3, 4, 5])
arr.resize(3)  # Resize to a shape of 3 elements
print(arr) 

[1 2 3]


# 11.String Functions

In [70]:
arr1 = np.array(['Hello', 'Good'])
arr2 = np.array(['World', 'Morning'])
result = np.char.add(arr1, arr2) # add element rowwise
print(result)

['HelloWorld' 'GoodMorning']


In [71]:
arr = np.array(['Hello', 'WORLD'])
result = np.char.lower(arr) # to lowercase
print(result)

['hello' 'world']


In [72]:
arr = np.array(['Hello', 'world'])
result = np.char.upper(arr) # to upper case
print(result)

['HELLO' 'WORLD']


In [74]:
arr = np.array(['hello world', 'good morning'])
result = np.char.title(arr) # convert first char to upper case and other to lower
print(result)

['Hello World' 'Good Morning']


In [76]:
arr = np.array(['  hello  ', ' world '])
result = np.char.strip(arr) # removes leading and trailing whitespaces in an array
print(result)

['hello' 'world']


In [77]:
arr = np.array(['Hello World', 'Good Morning'])
result = np.char.split(arr) # Splits each string in the array into a list of words using a specified delimiter (default is space).
print(result)

[list(['Hello', 'World']) list(['Good', 'Morning'])]


In [79]:
arr = np.array(['Hello World', 'Good Morning'])
result = np.char.replace(arr, 'World', 'Universe') # Replaces a substring within each string of the array with a new substring.

print(result)

['Hello Universe' 'Good Morning']


In [80]:
arr = np.array(['Hello World', 'Good Morning'])
result = np.char.count(arr, 'o') # count character in array
print(result)

[2 3]


# 12.Trigonometric Functions

In [81]:
import numpy as np

# Define an array of angles (in radians)
arr = np.array([0, np.pi/2, np.pi, 3*np.pi/2, np.pi/4, -np.pi/4])

# 1. Sine of each element
sin_result = np.sin(arr)
print("Sine:", sin_result)

# 2. Cosine of each element
cos_result = np.cos(arr)
print("Cosine:", cos_result)

# 3. Tangent of each element
tan_result = np.tan(arr)
print("Tangent:", tan_result)

# 4. Inverse Sine (arcsin) of each element
arcsin_result = np.arcsin(np.array([0, 0.5, 1]))  # Example with valid inputs
print("Arcsine:", arcsin_result)

# 5. Inverse Cosine (arccos) of each element
arccos_result = np.arccos(np.array([1, 0.5, 0]))  # Example with valid inputs
print("Arccosine:", arccos_result)

# 6. Inverse Tangent (arctan) of each element
arctan_result = np.arctan(np.array([0, 1, -1]))
print("Arctangent:", arctan_result)

# 7. Hyperbolic Sine of each element
sinh_result = np.sinh(arr)
print("Hyperbolic Sine:", sinh_result)

# 8. Hyperbolic Cosine of each element
cosh_result = np.cosh(arr)
print("Hyperbolic Cosine:", cosh_result)

# 9. Hyperbolic Tangent of each element
tanh_result = np.tanh(arr)
print("Hyperbolic Tangent:", tanh_result)

# 10. Inverse Hyperbolic Sine of each element
arcsinh_result = np.arcsinh(np.array([0, 1, -1]))
print("Arcsinh:", arcsinh_result)

# 11. Inverse Hyperbolic Cosine of each element
arccosh_result = np.arccosh(np.array([1, 2, 3]))
print("Arccosh:", arccosh_result)

# 12. Inverse Hyperbolic Tangent of each element
arctanh_result = np.arctanh(np.array([0, 0.5, -0.5]))
print("Arctanh:", arctanh_result)


Sine: [ 0.00000000e+00  1.00000000e+00  1.22464680e-16 -1.00000000e+00
  7.07106781e-01 -7.07106781e-01]
Cosine: [ 1.00000000e+00  6.12323400e-17 -1.00000000e+00 -1.83697020e-16
  7.07106781e-01  7.07106781e-01]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15
  1.00000000e+00 -1.00000000e+00]
Arcsine: [0.         0.52359878 1.57079633]
Arccosine: [0.         1.04719755 1.57079633]
Arctangent: [ 0.          0.78539816 -0.78539816]
Hyperbolic Sine: [ 0.          2.3012989  11.54873936 55.6543976   0.86867096 -0.86867096]
Hyperbolic Cosine: [ 1.          2.50917848 11.59195328 55.66338089  1.32460909  1.32460909]
Hyperbolic Tangent: [ 0.          0.91715234  0.99627208  0.99983861  0.6557942  -0.6557942 ]
Arcsinh: [ 0.          0.88137359 -0.88137359]
Arccosh: [0.         1.3169579  1.76274717]
Arctanh: [ 0.          0.54930614 -0.54930614]


# 13. Math in array in numpy

In [83]:
import numpy as np

# ----------------------------------------------
# 1. Basic Mathematical Operations
# ----------------------------------------------

arr1 = np.array([1, 2, 3])  # First array
arr2 = np.array([4, 5, 6])  # Second array

# 1. Addition
addition_result = arr1 + arr2
print("Addition:", addition_result)

# 2. Subtraction
subtraction_result = arr1 - arr2
print("Subtraction:", subtraction_result)

# 3. Multiplication
multiplication_result = arr1 * arr2
print("Multiplication:", multiplication_result)

# 4. Division
division_result = arr1 / arr2
print("Division:", division_result)

# 5. Exponentiation
exponentiation_result = arr1 ** 2
print("Exponentiation:", exponentiation_result)

# ----------------------------------------------
# 2. More Mathematical Functions
# ----------------------------------------------

# 6. Square root
sqrt_result = np.sqrt(arr2)
print("\nSquare Root:", sqrt_result)

# 7. Exponential (e^x)
exp_result = np.exp(arr1)
print("Exponential (e^x):", exp_result)

# 8. Logarithm (Natural log)
log_result = np.log(arr2)
print("Logarithm (Natural log):", log_result)

# 9. Mean of elements
mean_result = np.mean(arr1)
print("\nMean:", mean_result)

# 10. Sum of elements
sum_result = np.sum(arr1)
print("Sum:", sum_result)

# 11. Standard Deviation
std_result = np.std(arr1)
print("Standard Deviation:", std_result)

# 12. Maximum value
max_result = np.max(arr2)
print("Maximum:", max_result)

# 13. Minimum value
min_result = np.min(arr2)
print("Minimum:", min_result)




Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [1 4 9]

Square Root: [2.         2.23606798 2.44948974]
Exponential (e^x): [ 2.71828183  7.3890561  20.08553692]
Logarithm (Natural log): [1.38629436 1.60943791 1.79175947]

Mean: 2.0
Sum: 6
Standard Deviation: 0.816496580927726
Maximum: 6
Minimum: 4


# 14.Statistical Functions

In [84]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 1. Mean
mean_value = np.mean(arr)
print("Mean:", mean_value)

# 2. Median
median_value = np.median(arr)
print("Median:", median_value)

# 3. Variance
variance_value = np.var(arr)
print("Variance:", variance_value)

# 4. Standard Deviation
std_dev_value = np.std(arr)
print("Standard Deviation:", std_dev_value)

# 5. Minimum Value
min_value = np.min(arr)
print("Minimum:", min_value)

# 6. Maximum Value
max_value = np.max(arr)
print("Maximum:", max_value)

# 7. Sum
sum_value = np.sum(arr)
print("Sum:", sum_value)

# 8. Product
product_value = np.prod(arr)
print("Product:", product_value)

# 9. Percentile (50th percentile - Median)
percentile_value = np.percentile(arr, 50)
print("50th Percentile:", percentile_value)

# 10. Cumulative Sum
cumsum_value = np.cumsum(arr)
print("Cumulative Sum:", cumsum_value)

# 11. Cumulative Product
cumprod_value = np.cumprod(arr)
print("Cumulative Product:", cumprod_value)

# Example for two arrays:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# 12. Correlation Coefficient
corrcoef_value = np.corrcoef(arr1, arr2)
print("Correlation Coefficient:\n", corrcoef_value)

# 13. Covariance Matrix
cov_value = np.cov(arr1, arr2)
print("Covariance Matrix:\n", cov_value)

# 14. Interquartile Range (IQR)
iqr_value = np.percentile(arr, 75) - np.percentile(arr, 25)
print("Interquartile Range (IQR):", iqr_value)

Mean: 5.5
Median: 5.5
Variance: 8.25
Standard Deviation: 2.8722813232690143
Minimum: 1
Maximum: 10
Sum: 55
Product: 3628800
50th Percentile: 5.5
Cumulative Sum: [ 1  3  6 10 15 21 28 36 45 55]
Cumulative Product: [      1       2       6      24     120     720    5040   40320  362880
 3628800]
Correlation Coefficient:
 [[ 1. -1.]
 [-1.  1.]]
Covariance Matrix:
 [[ 2.5 -2.5]
 [-2.5  2.5]]
Interquartile Range (IQR): 4.5


# 15.Numpy Sorting

In [85]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)

Sorted Array: [1 1 2 3 3 4 5 5 5 6 9]


In [86]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

sorted_indices = np.argsort(arr) # Returns the indices that would sort an array.
print("Indices that would sort the array:", sorted_indices)

Indices that would sort the array: [ 1  3  6  0  9  2  4  8 10  7  5]


In [87]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

partitioned_arr = np.partition(arr, 4)  # Partition around the 4th smallest element
print("Partitioned Array:", partitioned_arr)

Partitioned Array: [1 1 2 3 3 4 5 5 6 5 9]


In [88]:
# Sort in descending order using np.sort
desc_sorted_arr = np.sort(arr)[::-1]
print("Descending Sorted Array:", desc_sorted_arr)

Descending Sorted Array: [9 6 5 5 5 4 3 3 2 1 1]


In [89]:
sorted_arr_mergesort = np.sort(arr, kind='mergesort')
print("Mergesort Sorted Array:", sorted_arr_mergesort)

Mergesort Sorted Array: [1 1 2 3 3 4 5 5 5 6 9]


# 16. Filteration

In [90]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Filter elements greater than 3 and less than 8, boolean indexing or masking
filtered_arr_multiple_conditions = arr[(arr > 3) & (arr < 8)]
print("Filtered Array (greater than 3 and less than 8):", filtered_arr_multiple_conditions)

Filtered Array (greater than 3 and less than 8): [4 5 6 7]


In [91]:
indices = np.where(arr > 5)
print("Indices of elements greater than 5:", indices)

# Replace elements greater than 5 with 0
arr_filtered = np.where(arr > 5, 0, arr)
print("Array with elements greater than 5 replaced by 0:", arr_filtered)

Indices of elements greater than 5: (array([5, 6, 7, 8], dtype=int64),)
Array with elements greater than 5 replaced by 0: [1 2 3 4 5 0 0 0 0]


In [92]:
# Extract elements greater than 5
extracted_elements = np.extract(arr > 5, arr)
print("Extracted Elements (greater than 5):", extracted_elements)


Extracted Elements (greater than 5): [6 7 8 9]


In [93]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Filter elements greater than 5 in 2D array
filtered_2d = arr_2d[arr_2d > 5]
print("Filtered 2D Array (greater than 5):", filtered_2d)

Filtered 2D Array (greater than 5): [6 7 8 9]


In [94]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Check if all elements in the array are greater than 2
all_elements_greater_than_2 = np.all(arr_2d > 2)
print("Are all elements greater than 2?", all_elements_greater_than_2)

# Check if any element in the array is greater than 8
any_element_greater_than_8 = np.any(arr_2d > 8)
print("Is any element greater than 8?", any_element_greater_than_8)

Are all elements greater than 2? False
Is any element greater than 8? True


In [95]:
non_zero_indices = np.nonzero(arr)
print("Indices of non-zero elements:", non_zero_indices)

# Get the non-zero elements themselves
non_zero_elements = arr[non_zero_indices]
print("Non-zero elements:", non_zero_elements)

Indices of non-zero elements: (array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)
Non-zero elements: [1 2 3 4 5 6 7 8 9]


# 17. View in numpy

In [96]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a view (shallow copy) of the original array
arr_view = arr[2:4]

# Modify the view
arr_view[0] = 99

print("Original Array after view modification:", arr)
print("View Array:", arr_view)

Original Array after view modification: [ 1  2 99  4  5]
View Array: [99  4]


# 18. Copy in numpy

In [97]:
# Create a copy of the original array
arr_copy = np.copy(arr)

# Modify the copy
arr_copy[0] = 100

print("Original Array after copy modification:", arr)
print("Copy Array:", arr_copy)

Original Array after copy modification: [ 1  2 99  4  5]
Copy Array: [100   2  99   4   5]
